package model;

import ui.WordleAppOriginal;

import java.util.ArrayList;
import java.util.List;

// list of colour codes generated by guess class
public class ListOfGuess {
    private List<GuessOriginal> guessLog;
    private List<List<String>> listOfColourCode;

    public ListOfGuess() {
        this.guessLog = new ArrayList<>();
        this.listOfColourCode = new ArrayList<>();
    }

    public List<List<String>> getListOfColourCode() {
        return this.listOfColourCode;
    }

    public void addGuessToLog(GuessOriginal guess) {
        guessLog.add(guess);
    }

    public void analyzeLog() {
        for (GuessOriginal g : this.guessLog) {
            g.analyzeGuess();
            listOfColourCode.add(g.getColourCode());
            System.out.println(listOfColourCode);
        }
    }
}
