//package model;
//
//import ui.WordleApp;
//
//import java.util.ArrayList;
//import java.util.List;
//
//// list of colour codes generated by guess class
//public class ListOfGuess {
//    private List<Guess> guessLog;
//
//    public ListOfGuess() {
//        this.guessLog = new ArrayList<>();
//    }
//
//    public void addGuessToLog() {
//        WordleApp wordleApp = new WordleApp();
//        Guess addNewGuess = new Guess();
//        guessLog.add(addNewGuess);
//
//    }
//}
